org: osvaldobazzanbini
app: schedulerapp
service: scheduler-web-app

provider:
  name: aws
  runtime: nodejs20.x

functions:
  create-appointment:
    handler: src/lambdas/Appointments/scheduler-create-appointment.handler
    events:
      - httpApi:
          path: /appointments
          method: post

  # show-appointments:
  #   handler: src/lambdas/Appointments/scheduler-show-appointments.handler
  #   events:
  #     - httpApi:
  #         path: /appointments
  #         method: get
  
  # delete-appointments:
  #   handler: src/lambdas/Appointments/scheduler-delete-appointment.handler
  #   events:
  #     - httpApi:
  #         path: /appointments
  #         method: delete
  
  # update-appointments:
  #   handler: src/lambdas/Appointments/scheduler-update-appointment.handler
  #   events:
  #     - httpApi:
  #         path: /appointments
  #         method: put

# functions:
#   hello:
#     handler: src/lambdas/SAppointments/CreateAppointment.handler
#     events:
#       - httpApi:
#           path: /appointments
#           method: post
