name: Deploy Backend Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Rodar Testes
        run: yarn test

      - name: Serverless Deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_SECRET }}
          ALLOWED_ORIGIN: ${{ secrets.PROD_ALLOWED_ORIGIN }}