name: CI

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup local DynamoDB
      run: docker run -d -p 8000:8000 amazon/dynamodb-local
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: yarn

    - name: Set up DynamoDB (for AWS SDKs)
      run: |
        export DYNAMODB_ENDPOINT=http://localhost:8000
        export AWS_ACCESS_KEY_ID=2uz49p
        export AWS_SECRET_ACCESS_KEY=c7g4g

    - name: Run tests
      run: |
        yarn test