name: CI

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup local DynamoDB
      run: docker run -d -p 8000:8000 amazon/dynamodb-local
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: yarn

    - name: Set up DynamoDB (for AWS SDKs)
      run: |
        export DYNAMODB_ENDPOINT=http://localhost:8000
        export AWS_ACCESS_KEY_ID=${{ secrets.KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.ACCESS_KEY }}

    - name: Run show tests
      run: |
        yarn test:show
    
    - name: Run create tests
      run: |
        yarn test:create

    - name: Run update tests
      run: |
        yarn test:update

    - name: Run delete tests
      run: |
        yarn test:delete