name: CI

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    services:

      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
        options: -jar DynamoDBLocal.jar -inMemory -sharedDb

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.2' # Specify your Node.js version here

    - name: Install dependencies
      run: yarn

    - name: Set up DynamoDB (for AWS SDKs)
      run: |
        export DYNAMODB_ENDPOINT=http://localhost:8000
        export AWS_ACCESS_KEY_ID=2uz49p
        export AWS_SECRET_ACCESS_KEY=c7g4g

    - name: Run show test
      run: yarn test:show
